// Generated by gmmproc 2.82.0 -- DO NOT MODIFY!
#ifndef _GTKMM_TREEPATH_P_H
#define _GTKMM_TREEPATH_P_H
#ifndef GTKMM_DISABLE_DEPRECATED


#endif // GTKMM_DISABLE_DEPRECATED


#endif /* _GTKMM_TREEPATH_P_H */

